In [12]:
import numpy as np
import pandas as pd
import backtrader as backtrader
import yfinance as yf
import os
import ta

In [34]:
data = pd.read_csv('GC_1min_sample.csv', index_col='timestamp', parse_dates=True)
data.index.name= 'Time'
data.head(5)

                       open    high     low   close  volume
Time
2025-05-04 18:00:00  3247.1  3249.8  3246.1  3249.7     192
2025-05-04 18:01:00  3249.2  3251.3  3246.6  3248.0     250
2025-05-04 18:02:00  3248.0  3248.8  3245.6  3245.9      98
2025-05-04 18:03:00  3246.0  3247.7  3245.7  3246.2     103
2025-05-04 18:04:00  3245.7  3246.0  3243.9  3244.2     153

In [35]:
for i in range(10,31,10):
  data[f'std deviation {i}'] = data['close'].rolling(window=i).std()
for i in range(10,31,10):
  data[f'moving average {i}'] = data['close'].rolling(window=i).mean()
data['body ratio']= np.abs((data['close'] - data['open'])/( data['high']-data['low']))
result = np.where(data['close']>data['open'],(data['high'] - data['close'])/( data['open']-data['low']),(data['high'] - data['open'])/( data['close']-data['low']))
result = np.where(np.isinf(result), 0, result)
data['upper wick to lower wick ratio']= result
data['Returns'] = (data['close']/data['close'].shift(1))
data['Log Returns'] = np.log(data['Returns'])
data['Returns']=(1-data['Returns'])*100
data.dropna(inplace=True)

In [36]:
data.head()

,open,high,low,close,volume,std deviation 10,std deviation 20,std deviation 30,moving average 10,moving average 20,moving average 30,body ratio,upper wick to lower wick ratio,Returns,Log Returns
Time,,,,,,,,,,,,,,,
2025-05-04 18:30:00,3246.2,3247.9,3245.8,3247.5,52,0.634210,1.195650,1.232715,3247.70,3246.830,3246.520000,0.619048,1.000000,-0.036965,0.000370
2025-05-04 18:31:00,3247.6,3248.2,3247.3,3248.1,47,0.646443,1.053753,1.236983,3247.73,3247.025,3246.523333,0.555556,0.333333,-0.018476,0.000185
2025-05-04 18:33:00,3247.1,3248.4,3247.1,3248.3,36,0.705927,0.894663,1.271148,3247.65,3247.260,3246.626667,0.923077,0.000000,-0.043118,0.000431
2025-05-04 18:34:00,3248.4,3248.7,3247.9,3248.0,51,0.681175,0.817956,1.208799,3247.62,3247.380,3246.753333,0.500000,3.000000,0.009236,-0.000092
2025-05-04 18:35:00,3248.1,3248.3,3246.7,3246.7,20,0.704036,0.709633,1.192428,3247.47,3247.440,3246.786667,0.875000,0.000000,0.040025,-0.000400

In [16]:
data.shape

(14589, 13)