In [6]:
import numpy as np
import pandas as pd
import backtrader as backtrader
import yfinance as yf
import os

In [64]:
data = pd.read_csv('GC_1min_sample.csv', index_col='timestamp', parse_dates=True)
data.index.name= 'Time'
data.head(5)

                       open    high     low   close  volume
Time
2025-05-04 18:00:00  3247.1  3249.8  3246.1  3249.7     192
2025-05-04 18:01:00  3249.2  3251.3  3246.6  3248.0     250
2025-05-04 18:02:00  3248.0  3248.8  3245.6  3245.9      98
2025-05-04 18:03:00  3246.0  3247.7  3245.7  3246.2     103
2025-05-04 18:04:00  3245.7  3246.0  3243.9  3244.2     153

In [ ]:
for i in range(10,31,10):
  data[f'std deviation {i}'] = data['close'].rolling(window=i).std()
for i in range(10,31,10):
  data[f'moving average {i}'] = data['close'].rolling(window=i).mean()
data['body ratio']= np.abs((data['close'] - data['open'])/( data['high']-data['low']))
data['higher wick to lower wick ratio']=np.round(np.abs((data['close'] - data['open'])/( data['high']-data['low'])),5)
data.dropna(inplace=True)

In [66]:
data.head()

,open,high,low,close,volume,std deviation 10,std deviation 20,std deviation 30,moving average 10,moving average 20,moving average 30,body ratio
Time,,,,,,,,,,,,
2025-05-04 18:29:00,3246.9,3246.9,3246.3,3246.3,24,0.644291,1.282791,1.352630,3247.68,3246.685,3246.593333,1.00000
2025-05-04 18:30:00,3246.2,3247.9,3245.8,3247.5,52,0.634210,1.195650,1.232715,3247.70,3246.830,3246.520000,0.61905
2025-05-04 18:31:00,3247.6,3248.2,3247.3,3248.1,47,0.646443,1.053753,1.236983,3247.73,3247.025,3246.523333,0.55556
2025-05-04 18:32:00,3248.2,3248.2,3246.9,3246.9,51,0.671648,0.941220,1.233074,3247.60,3247.120,3246.556667,1.00000
2025-05-04 18:33:00,3247.1,3248.4,3247.1,3248.3,36,0.705927,0.894663,1.271148,3247.65,3247.260,3246.626667,0.92308

In [45]:
data.shape

(15166, 8)